import type { Dish, MenuCategory, MenuCategoryId, MenuGroup } from "@/types";

/**
 * Menu content.
 *
 * Prices are whole Ghana cedis (the base currency); the currency switcher
 * converts at read time. Replace this module with a CMS query and every
 * consumer — menu explorer, cart, schema.org markup — keeps working.
 */

export const MENU_GROUPS: readonly MenuGroup[] = [
  { id: "kitchen", name: "The Kitchen", description: "Plates that move with the clock, from first light to last service." },
  { id: "fire", name: "The Fire", description: "Charcoal, hardwood and time. Everything here meets a flame." },
  { id: "roots", name: "The Roots", description: "West African cooking, treated with the reverence it has always deserved." },
  { id: "sweet", name: "The Finish", description: "Pastry, chocolate and the last word of the evening." },
  { id: "bar", name: "The Bar", description: "A cellar, a still room and a bartender with opinions." },
];

export const MENU_CATEGORIES: readonly MenuCategory[] = [
  { id: "starters", name: "Starters", group: "kitchen", tagline: "Small plates, loud flavour", image: "/images/dish-starter.webp" },
  { id: "breakfast", name: "Breakfast", group: "kitchen", tagline: "From 07:30, every day", image: "/images/dish-brunch.webp" },
  { id: "lunch", name: "Lunch", group: "kitchen", tagline: "In and out in under an hour", image: "/images/dish-brunch.webp" },
  { id: "dinner", name: "Dinner", group: "kitchen", tagline: "The room at its best", image: "/images/hero-signature.webp" },
  { id: "seafood", name: "Seafood", group: "fire", tagline: "Landed at Tema this morning", image: "/images/dish-lobster.webp" },
  { id: "grill", name: "Grill & Smoke", group: "fire", tagline: "Live fire, no shortcuts", image: "/images/dish-suya.webp" },
  { id: "steak", name: "Dry-Aged Steak", group: "fire", tagline: "45 days, cut to order", image: "/images/dish-steak.webp" },
  { id: "pizza", name: "Wood-Fired Pizza", group: "fire", tagline: "72-hour sourdough", image: "/images/dish-pizza.webp" },
  { id: "pasta", name: "Pasta", group: "kitchen", tagline: "Rolled each morning", image: "/images/dish-pasta.webp" },
  { id: "rice", name: "Rice & Grains", group: "roots", tagline: "Smoke, stock, patience", image: "/images/dish-jollof.webp" },
  { id: "local", name: "Local Classics", group: "roots", tagline: "Our grandmothers' recipes", image: "/images/dish-jollof.webp" },
  { id: "desserts", name: "Desserts", group: "sweet", tagline: "Worth saving room for", image: "/images/dish-dessert.webp" },
  { id: "drinks", name: "Soft Drinks", group: "bar", tagline: "Pressed, brewed, chilled", image: "/images/bar-counter.webp" },
  { id: "cocktails", name: "Cocktails", group: "bar", tagline: "Smoke, bitters, botanicals", image: "/images/dish-cocktail.webp" },
  { id: "wine", name: "Wine", group: "bar", tagline: "420 labels, 18 by the glass", image: "/images/event-wine.webp" },
  { id: "mocktails", name: "Zero Proof", group: "bar", tagline: "Every bit as considered", image: "/images/dish-cocktail.webp" },
  { id: "coffee", name: "Coffee & Tea", group: "bar", tagline: "Single origin, roasted weekly", image: "/images/dish-brunch.webp" },
];

export const DISHES: readonly Dish[] = [
  /* ------------------------------- STARTERS ------------------------------- */
  {
    id: "burrata-scotch-honey",
    name: "Burrata, Scotch Bonnet Honey",
    category: "starters",
    description:
      "Torn burrata over heirloom tomato petals, finished with honey we infuse with scorched scotch bonnet. Sweet first, warm after.",
    ingredients: ["Buffalo burrata", "Heirloom tomatoes", "Scotch bonnet honey", "Basil oil", "Toasted seed crumble"],
    price: 148,
    calories: 420,
    prepTime: 10,
    image: "/images/dish-starter.webp",
    spice: 1,
    badges: ["chef-recommendation", "popular"],
    dietary: ["vegetarian", "gluten-free"],
    rating: 4.9,
    reviewCount: 412,
    pairing: "Sancerre, Domaine Vacheron 2022",
    serves: "One, generously",
  },
  {
    id: "kelewele-croquettes",
    name: "Kelewele Croquettes",
    category: "starters",
    description:
      "Spiced plantain and smoked cheese croquettes with a ginger-peanut emulsion. The street snack of Accra, in black tie.",
    ingredients: ["Ripe plantain", "Smoked wagashi", "Ginger", "Grains of selim", "Roast peanut emulsion"],
    price: 96,
    calories: 480,
    prepTime: 12,
    image: "/images/dish-starter.webp",
    spice: 2,
    badges: ["best-seller"],
    dietary: ["vegetarian"],
    rating: 4.8,
    reviewCount: 638,
    pairing: "Dzifoods Sour — our house cocktail",
    serves: "Five croquettes",
  },
  {
    id: "tuna-crudo-shito",
    name: "Yellowfin Crudo, Green Shito",
    category: "starters",
    description:
      "Line-caught yellowfin sliced thin, dressed in green shito, cucumber water and lime leaf. Cold, sharp, alive.",
    ingredients: ["Yellowfin tuna", "Green shito", "Cucumber", "Lime leaf", "Nigerian pepper"],
    price: 172,
    calories: 260,
    prepTime: 9,
    image: "/images/dish-starter.webp",
    spice: 2,
    badges: ["signature"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.9,
    reviewCount: 287,
    pairing: "Grüner Veltliner, Weingut Hirsch 2023",
  },
  {
    id: "smoked-catfish-tartlet",
    name: "Smoked Catfish Tartlet",
    category: "starters",
    description:
      "Volta catfish smoked over coconut husk, folded into crème fraîche in a butter shell, topped with pickled onion.",
    ingredients: ["Volta catfish", "Coconut husk smoke", "Crème fraîche", "Pickled red onion", "Dill"],
    price: 118,
    calories: 340,
    prepTime: 11,
    image: "/images/dish-starter.webp",
    spice: 0,
    badges: [],
    dietary: [],
    rating: 4.7,
    reviewCount: 154,
  },

  /* ------------------------------- BREAKFAST ------------------------------ */
  {
    id: "dzi-breakfast",
    name: "The DZI Breakfast",
    category: "breakfast",
    description:
      "Slow-folded eggs with chives, thick-cut smoked bacon, vine tomatoes, avocado on sourdough and a poached egg that runs.",
    ingredients: ["Free-range eggs", "Smoked bacon", "Vine tomatoes", "Avocado", "Sourdough"],
    price: 132,
    calories: 720,
    prepTime: 14,
    image: "/images/dish-brunch.webp",
    spice: 0,
    badges: ["best-seller"],
    dietary: [],
    rating: 4.8,
    reviewCount: 921,
    pairing: "Flat white, Ethiopia Guji",
  },
  {
    id: "waakye-benedict",
    name: "Waakye Benedict",
    category: "breakfast",
    description:
      "Our most argued-about plate: waakye rice cake, poached eggs, shito hollandaise and crisp shallots.",
    ingredients: ["Waakye rice", "Poached eggs", "Shito hollandaise", "Crisp shallot", "Coriander"],
    price: 124,
    calories: 640,
    prepTime: 16,
    image: "/images/dish-brunch.webp",
    spice: 2,
    badges: ["chef-recommendation", "signature"],
    dietary: [],
    rating: 4.9,
    reviewCount: 503,
  },
  {
    id: "coconut-oats",
    name: "Toasted Coconut Oats",
    category: "breakfast",
    description:
      "Steel-cut oats slow-cooked in coconut milk with roasted banana, cocoa nib and a spoon of shea honey.",
    ingredients: ["Steel-cut oats", "Coconut milk", "Roast banana", "Cocoa nib", "Shea honey"],
    price: 78,
    calories: 430,
    prepTime: 10,
    image: "/images/dish-brunch.webp",
    spice: 0,
    badges: [],
    dietary: ["vegan", "dairy-free"],
    rating: 4.6,
    reviewCount: 208,
  },
  {
    id: "brioche-french-toast",
    name: "Brown Butter Brioche Toast",
    category: "breakfast",
    description: "Thick-cut brioche in brown butter, caramelised pineapple, mascarpone and dark palm sugar syrup.",
    ingredients: ["House brioche", "Brown butter", "Pineapple", "Mascarpone", "Palm sugar"],
    price: 98,
    calories: 690,
    prepTime: 13,
    image: "/images/dish-brunch.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["vegetarian"],
    rating: 4.8,
    reviewCount: 366,
  },

  /* --------------------------------- LUNCH -------------------------------- */
  {
    id: "grilled-chicken-salad",
    name: "Charred Chicken & Grain Salad",
    category: "lunch",
    description:
      "Suya-rubbed chicken thigh over fonio, roast squash, pomegranate and a herb yoghurt that cools it all down.",
    ingredients: ["Chicken thigh", "Fonio", "Roast squash", "Pomegranate", "Herb yoghurt"],
    price: 138,
    calories: 560,
    prepTime: 18,
    image: "/images/dish-starter.webp",
    spice: 2,
    badges: ["popular"],
    dietary: ["gluten-free"],
    rating: 4.7,
    reviewCount: 274,
  },
  {
    id: "dzi-burger",
    name: "The DZI Burger",
    category: "lunch",
    description:
      "Dry-aged beef blend, smoked wagashi, kelewele relish and shito aioli in a milk bun. Two napkins minimum.",
    ingredients: ["Dry-aged beef", "Smoked wagashi", "Kelewele relish", "Shito aioli", "Milk bun"],
    price: 165,
    calories: 880,
    prepTime: 17,
    image: "/images/dish-steak.webp",
    spice: 2,
    badges: ["best-seller"],
    dietary: [],
    rating: 4.9,
    reviewCount: 1104,
    pairing: "Malbec, Catena Alta 2021",
  },
  {
    id: "market-express-lunch",
    name: "Market Express — Two Courses",
    category: "lunch",
    description:
      "Whatever looked best at Makola this morning, in two courses, served inside forty-five minutes. Ask your server.",
    ingredients: ["Chef's market selection", "Seasonal produce", "Daily bread", "Cultured butter"],
    price: 185,
    calories: 700,
    prepTime: 22,
    image: "/images/ingredients.webp",
    spice: 1,
    badges: ["chef-recommendation", "limited"],
    dietary: [],
    rating: 4.8,
    reviewCount: 189,
    serves: "One, two courses",
  },
  {
    id: "red-red-bowl",
    name: "Red Red Bowl",
    category: "lunch",
    description: "Bambara bean stew in palm oil with fried plantain and a soft egg. Comfort with a backbone.",
    ingredients: ["Bambara beans", "Palm oil", "Fried plantain", "Soft egg", "Gari"],
    price: 112,
    calories: 620,
    prepTime: 15,
    image: "/images/dish-jollof.webp",
    spice: 2,
    badges: [],
    dietary: ["vegetarian", "gluten-free"],
    rating: 4.7,
    reviewCount: 331,
  },

  /* -------------------------------- DINNER -------------------------------- */
  {
    id: "miso-black-cod",
    name: "Miso-Glazed Black Cod",
    category: "dinner",
    description:
      "Three days in white miso, then finished over charcoal until the glaze lacquers. The plate people come back for.",
    ingredients: ["Black cod", "White miso", "Mirin", "Micro herbs", "Charred lime"],
    price: 385,
    calories: 520,
    prepTime: 24,
    image: "/images/hero-signature.webp",
    spice: 0,
    badges: ["signature", "chef-recommendation", "best-seller"],
    dietary: ["dairy-free"],
    rating: 5,
    reviewCount: 842,
    pairing: "Chablis 1er Cru, Fourchaume 2021",
    serves: "One",
  },
  {
    id: "seven-fires-tasting",
    name: "The Seven Fires Tasting",
    category: "dinner",
    description:
      "Seven courses cooked entirely over live flame. Two and a half hours, one long conversation. Whole table only.",
    ingredients: ["Chef's seasonal progression", "Live-fire cookery", "Optional wine flight", "Bread service"],
    price: 890,
    calories: 1450,
    prepTime: 150,
    image: "/images/kitchen-pass.webp",
    spice: 1,
    badges: ["signature", "limited"],
    dietary: [],
    rating: 5,
    reviewCount: 264,
    pairing: "Sommelier flight, seven glasses (+₵520)",
    serves: "Per guest, whole table",
  },
  {
    id: "guinea-fowl",
    name: "Charcoal Guinea Fowl",
    category: "dinner",
    description:
      "Whole guinea fowl brined in dawadawa, roasted over embers, carved at the table with its own dripping gravy.",
    ingredients: ["Guinea fowl", "Dawadawa brine", "Ember-roast onions", "Thyme", "Pan gravy"],
    price: 340,
    calories: 780,
    prepTime: 40,
    image: "/images/dish-suya.webp",
    spice: 1,
    badges: ["chef-recommendation"],
    dietary: ["gluten-free"],
    rating: 4.9,
    reviewCount: 197,
    serves: "Two to share",
  },
  {
    id: "aubergine-ash",
    name: "Aubergine in Ash",
    category: "dinner",
    description:
      "Buried in embers until it collapses, dressed with sesame, burnt honey and toasted egusi. Nobody misses the meat.",
    ingredients: ["Aubergine", "Sesame", "Burnt honey", "Egusi seed", "Coriander stem oil"],
    price: 168,
    calories: 380,
    prepTime: 26,
    image: "/images/dish-starter.webp",
    spice: 1,
    badges: ["popular"],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    rating: 4.8,
    reviewCount: 226,
  },

  /* -------------------------------- SEAFOOD ------------------------------- */
  {
    id: "fire-shellfish-platter",
    name: "Fire Shellfish Platter",
    category: "seafood",
    description:
      "Split lobster tails, scallops and jumbo prawns glazed in chilli-garlic butter, charred lemon on the side.",
    ingredients: ["Lobster tail", "Scallops", "Jumbo prawns", "Chilli-garlic butter", "Charred lemon"],
    price: 640,
    calories: 820,
    prepTime: 28,
    image: "/images/dish-lobster.webp",
    spice: 2,
    badges: ["best-seller", "signature"],
    dietary: ["gluten-free"],
    rating: 4.9,
    reviewCount: 588,
    pairing: "Champagne, Billecart-Salmon Brut Rosé",
    serves: "Two to share",
  },
  {
    id: "grilled-tilapia",
    name: "Whole Charcoal Tilapia",
    category: "seafood",
    description: "Scored, salted, grilled hard over coals and served with fresh shito and kenkey. Eat with your hands.",
    ingredients: ["Whole tilapia", "Fresh shito", "Kenkey", "Lime", "Onion salad"],
    price: 245,
    calories: 610,
    prepTime: 25,
    image: "/images/dish-jollof.webp",
    spice: 3,
    badges: ["popular"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.9,
    reviewCount: 733,
  },
  {
    id: "prawns-akple",
    name: "Butter Prawns & Akple",
    category: "seafood",
    description: "Tiger prawns in dawadawa butter with soft akple and a spoonful of light pepper broth.",
    ingredients: ["Tiger prawns", "Dawadawa butter", "Akple", "Pepper broth", "Spring onion"],
    price: 285,
    calories: 590,
    prepTime: 22,
    image: "/images/dish-lobster.webp",
    spice: 2,
    badges: ["chef-recommendation"],
    dietary: [],
    rating: 4.8,
    reviewCount: 241,
  },
  {
    id: "octopus-ember",
    name: "Ember Octopus",
    category: "seafood",
    description: "Slow-braised then flashed over fire, with smoked pepper romesco and salted lime.",
    ingredients: ["Octopus", "Smoked pepper romesco", "Salted lime", "Parsley oil", "Sea salt"],
    price: 265,
    calories: 440,
    prepTime: 30,
    image: "/images/dish-lobster.webp",
    spice: 1,
    badges: [],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.7,
    reviewCount: 163,
  },

  /* ------------------------------ GRILL & SMOKE --------------------------- */
  {
    id: "suya-skewers",
    name: "Beef Suya Skewers",
    category: "grill",
    description:
      "Spice-crusted beef over open flame, dusted again in yaji at the pass. Order two — one never survives the table.",
    ingredients: ["Beef sirloin", "Yaji spice", "Roast peanut", "Red onion", "Lime"],
    price: 155,
    calories: 520,
    prepTime: 16,
    image: "/images/dish-suya.webp",
    spice: 3,
    badges: ["best-seller", "signature"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 5,
    reviewCount: 1291,
    pairing: "Syrah, Domaine Jamet 2020",
    serves: "Four skewers",
  },
  {
    id: "lamb-chops-ember",
    name: "Ember Lamb Chops",
    category: "grill",
    description: "Three thick chops over hardwood, mint and grains of selim, with burnt aubergine cream.",
    ingredients: ["Lamb chops", "Grains of selim", "Mint", "Burnt aubergine cream", "Sea salt"],
    price: 320,
    calories: 700,
    prepTime: 24,
    image: "/images/dish-suya.webp",
    spice: 1,
    badges: ["chef-recommendation"],
    dietary: ["gluten-free"],
    rating: 4.9,
    reviewCount: 318,
  },
  {
    id: "smoked-half-chicken",
    name: "Smoked Half Chicken",
    category: "grill",
    description: "Four hours over coconut husk, glazed in scotch bonnet and honey, with pickled cabbage.",
    ingredients: ["Free-range chicken", "Coconut husk smoke", "Scotch bonnet honey", "Pickled cabbage"],
    price: 215,
    calories: 760,
    prepTime: 20,
    image: "/images/dish-suya.webp",
    spice: 2,
    badges: ["popular"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.8,
    reviewCount: 402,
  },
  {
    id: "grilled-hispi",
    name: "Grilled Hispi Cabbage",
    category: "grill",
    description: "Charred until sweet, then dressed with fermented chilli, groundnut and crisp garlic.",
    ingredients: ["Hispi cabbage", "Fermented chilli", "Groundnut", "Crisp garlic", "Rice vinegar"],
    price: 92,
    calories: 260,
    prepTime: 18,
    image: "/images/dish-starter.webp",
    spice: 2,
    badges: [],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    rating: 4.7,
    reviewCount: 149,
  },

  /* --------------------------------- STEAK -------------------------------- */
  {
    id: "tomahawk",
    name: "45-Day Tomahawk",
    category: "steak",
    description:
      "1.2kg dry-aged tomahawk, crusted hard, rested long, carved at the table with herb butter melting over it.",
    ingredients: ["Dry-aged tomahawk", "Herb butter", "Flaked sea salt", "Charred rosemary", "Confit garlic"],
    price: 890,
    calories: 1320,
    prepTime: 38,
    image: "/images/dish-steak.webp",
    spice: 0,
    badges: ["signature", "best-seller"],
    dietary: ["gluten-free"],
    rating: 5,
    reviewCount: 471,
    pairing: "Cabernet Sauvignon, Ridge Estate 2019",
    serves: "Two to three",
  },
  {
    id: "ribeye",
    name: "Dry-Aged Ribeye 350g",
    category: "steak",
    description: "Deeply marbled, charcoal-seared, finished with bone marrow butter and peppercorn jus.",
    ingredients: ["Dry-aged ribeye", "Bone marrow butter", "Peppercorn jus", "Watercress"],
    price: 465,
    calories: 940,
    prepTime: 26,
    image: "/images/dish-steak.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["gluten-free"],
    rating: 4.9,
    reviewCount: 356,
  },
  {
    id: "fillet-truffle",
    name: "Fillet, Truffle & Marrow",
    category: "steak",
    description: "220g centre-cut fillet with roast bone marrow, black truffle and a red wine reduction.",
    ingredients: ["Beef fillet", "Bone marrow", "Black truffle", "Red wine reduction", "Chive"],
    price: 520,
    calories: 780,
    prepTime: 28,
    image: "/images/dish-steak.webp",
    spice: 0,
    badges: ["chef-recommendation"],
    dietary: ["gluten-free"],
    rating: 4.9,
    reviewCount: 208,
  },

  /* --------------------------------- PIZZA -------------------------------- */
  {
    id: "margherita-oro",
    name: "Margherita d'Oro",
    category: "pizza",
    description: "72-hour sourdough, San Marzano, buffalo mozzarella, basil and a green olive oil finish.",
    ingredients: ["Sourdough base", "San Marzano tomato", "Buffalo mozzarella", "Basil", "Olive oil"],
    price: 158,
    calories: 850,
    prepTime: 14,
    image: "/images/dish-pizza.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["vegetarian"],
    rating: 4.8,
    reviewCount: 617,
  },
  {
    id: "suya-pizza",
    name: "Suya Beef Pizza",
    category: "pizza",
    description: "Yaji-spiced beef, smoked wagashi, red onion and a coriander crème. Our best argument for fusion.",
    ingredients: ["Suya beef", "Smoked wagashi", "Red onion", "Coriander crème", "Yaji"],
    price: 195,
    calories: 980,
    prepTime: 16,
    image: "/images/dish-pizza.webp",
    spice: 3,
    badges: ["best-seller", "signature"],
    dietary: [],
    rating: 4.9,
    reviewCount: 524,
  },
  {
    id: "truffle-mushroom-pizza",
    name: "Truffle & Wild Mushroom",
    category: "pizza",
    description: "Fior di latte, wild mushroom, thyme, taleggio and shaved black truffle straight from the oven.",
    ingredients: ["Fior di latte", "Wild mushrooms", "Taleggio", "Thyme", "Black truffle"],
    price: 225,
    calories: 910,
    prepTime: 15,
    image: "/images/dish-pizza.webp",
    spice: 0,
    badges: ["chef-recommendation"],
    dietary: ["vegetarian"],
    rating: 4.9,
    reviewCount: 289,
  },

  /* --------------------------------- PASTA -------------------------------- */
  {
    id: "truffle-tagliatelle",
    name: "Truffle Tagliatelle",
    category: "pasta",
    description:
      "Hand-rolled tagliatelle in aged parmesan cream, buried under shaved black truffle. Finished at the table.",
    ingredients: ["Hand-rolled tagliatelle", "Aged parmesan", "Black truffle", "Butter", "Cracked pepper"],
    price: 295,
    calories: 780,
    prepTime: 18,
    image: "/images/dish-pasta.webp",
    spice: 0,
    badges: ["signature", "best-seller"],
    dietary: ["vegetarian"],
    rating: 5,
    reviewCount: 698,
    pairing: "Barolo, Vietti Castiglione 2019",
  },
  {
    id: "crab-linguine",
    name: "Chilli Crab Linguine",
    category: "pasta",
    description: "Picked blue crab, fermented chilli, garlic and lemon, tossed through fresh linguine.",
    ingredients: ["Blue crab", "Fermented chilli", "Garlic", "Lemon", "Fresh linguine"],
    price: 265,
    calories: 690,
    prepTime: 19,
    image: "/images/dish-pasta.webp",
    spice: 2,
    badges: ["popular"],
    dietary: [],
    rating: 4.8,
    reviewCount: 312,
  },
  {
    id: "oxtail-pappardelle",
    name: "Oxtail Pappardelle",
    category: "pasta",
    description: "Oxtail braised eight hours in red wine and dawadawa, folded into wide ribbons of pappardelle.",
    ingredients: ["Oxtail", "Red wine", "Dawadawa", "Pappardelle", "Gremolata"],
    price: 285,
    calories: 880,
    prepTime: 21,
    image: "/images/dish-pasta.webp",
    spice: 1,
    badges: ["chef-recommendation"],
    dietary: [],
    rating: 4.9,
    reviewCount: 274,
  },

  /* ----------------------------- RICE & GRAINS ---------------------------- */
  {
    id: "smoked-jollof",
    name: "Smoked Party Jollof",
    category: "rice",
    description:
      "Cooked over wood until the bottom catches — that is the point. Crowned with caramelised plantain and shito.",
    ingredients: ["Long-grain rice", "Wood smoke", "Roast pepper base", "Plantain", "Shito"],
    price: 145,
    calories: 680,
    prepTime: 20,
    image: "/images/dish-jollof.webp",
    spice: 2,
    badges: ["best-seller", "signature"],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    rating: 5,
    reviewCount: 1487,
    pairing: "Dzifoods Hibiscus Sour",
  },
  {
    id: "jollof-tilapia",
    name: "Jollof & Charcoal Tilapia",
    category: "rice",
    description: "Our jollof beside a whole grilled tilapia, fresh shito and lime. The plate on every table by 8pm.",
    ingredients: ["Party jollof", "Whole tilapia", "Fresh shito", "Plantain", "Lime"],
    price: 285,
    calories: 920,
    prepTime: 26,
    image: "/images/dish-jollof.webp",
    spice: 3,
    badges: ["best-seller"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.9,
    reviewCount: 866,
  },
  {
    id: "waakye-royale",
    name: "Waakye Royale",
    category: "rice",
    description: "Sorghum-stained rice and beans with gari, egg, avocado, spinach stew and a spoon of talia.",
    ingredients: ["Waakye rice", "Black-eyed beans", "Gari", "Egg", "Spinach stew"],
    price: 132,
    calories: 740,
    prepTime: 18,
    image: "/images/dish-jollof.webp",
    spice: 2,
    badges: ["popular"],
    dietary: ["vegetarian"],
    rating: 4.8,
    reviewCount: 429,
  },
  {
    id: "fonio-pilaf",
    name: "Fonio Pilaf",
    category: "rice",
    description: "Ancient West African grain steamed with herbs, preserved lemon and toasted almond.",
    ingredients: ["Fonio", "Preserved lemon", "Herbs", "Toasted almond", "Olive oil"],
    price: 88,
    calories: 380,
    prepTime: 14,
    image: "/images/ingredients.webp",
    spice: 0,
    badges: [],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    rating: 4.6,
    reviewCount: 118,
  },

  /* ----------------------------- LOCAL CLASSICS --------------------------- */
  {
    id: "banku-tilapia",
    name: "Banku & Grilled Tilapia",
    category: "local",
    description: "Fermented corn and cassava dough, soft and sour, with charcoal tilapia and pepper ground to order.",
    ingredients: ["Banku", "Whole tilapia", "Ground pepper", "Onion", "Tomato"],
    price: 235,
    calories: 810,
    prepTime: 24,
    image: "/images/dish-jollof.webp",
    spice: 3,
    badges: ["signature"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.9,
    reviewCount: 512,
  },
  {
    id: "light-soup",
    name: "Goat Light Soup",
    category: "local",
    description: "Clear, fiery, restorative. Goat on the bone simmered with ginger, pepper and garden eggs.",
    ingredients: ["Goat", "Ginger", "Scotch bonnet", "Garden eggs", "Tomato"],
    price: 175,
    calories: 420,
    prepTime: 30,
    image: "/images/dish-suya.webp",
    spice: 3,
    badges: ["chef-recommendation"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.9,
    reviewCount: 388,
  },
  {
    id: "palava-sauce",
    name: "Palava Sauce & Yam",
    category: "local",
    description: "Kontomire and egusi cooked down in palm oil, with fried yam and smoked mackerel.",
    ingredients: ["Kontomire", "Egusi", "Palm oil", "Fried yam", "Smoked mackerel"],
    price: 152,
    calories: 690,
    prepTime: 22,
    image: "/images/dish-jollof.webp",
    spice: 2,
    badges: [],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.7,
    reviewCount: 246,
  },
  {
    id: "groundnut-soup",
    name: "Groundnut Soup & Omo Tuo",
    category: "local",
    description: "Roasted groundnut broth with guinea fowl and hand-rolled rice balls. Sunday, any day of the week.",
    ingredients: ["Roast groundnut", "Guinea fowl", "Omo tuo", "Ginger", "Scotch bonnet"],
    price: 188,
    calories: 780,
    prepTime: 28,
    image: "/images/dish-suya.webp",
    spice: 2,
    badges: ["popular"],
    dietary: ["gluten-free", "dairy-free"],
    rating: 4.8,
    reviewCount: 297,
  },

  /* -------------------------------- DESSERTS ------------------------------ */
  {
    id: "chocolate-dome",
    name: "Tafo Chocolate Dome",
    category: "desserts",
    description:
      "Single-origin Ghanaian chocolate, cracked at the table so the salted caramel runs. Gold leaf, because why not.",
    ingredients: ["Tafo 72% chocolate", "Salted caramel", "Cocoa nib crumble", "Vanilla bean ice cream", "Gold leaf"],
    price: 138,
    calories: 620,
    prepTime: 12,
    image: "/images/dish-dessert.webp",
    spice: 0,
    badges: ["signature", "best-seller"],
    dietary: ["vegetarian"],
    rating: 5,
    reviewCount: 934,
    pairing: "Tawny Port, 20 Year",
  },
  {
    id: "coconut-tart",
    name: "Burnt Coconut Tart",
    category: "desserts",
    description: "Torched coconut custard in a shortbread shell with lime leaf sorbet.",
    ingredients: ["Coconut custard", "Shortbread", "Lime leaf sorbet", "Toasted coconut"],
    price: 108,
    calories: 480,
    prepTime: 10,
    image: "/images/dish-dessert.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["vegetarian"],
    rating: 4.8,
    reviewCount: 322,
  },
  {
    id: "plantain-parfait",
    name: "Caramelised Plantain Parfait",
    category: "desserts",
    description: "Layers of roast plantain, salted palm caramel and crème fraîche ice cream.",
    ingredients: ["Roast plantain", "Palm caramel", "Crème fraîche ice cream", "Peanut praline"],
    price: 112,
    calories: 540,
    prepTime: 11,
    image: "/images/dish-dessert.webp",
    spice: 0,
    badges: ["chef-recommendation"],
    dietary: ["vegetarian", "gluten-free"],
    rating: 4.9,
    reviewCount: 265,
  },
  {
    id: "hibiscus-sorbet",
    name: "Hibiscus & Ginger Sorbet",
    category: "desserts",
    description: "Sharp, cold and clean — sorrel and young ginger, with candied hibiscus petals.",
    ingredients: ["Hibiscus", "Young ginger", "Cane sugar", "Candied petals"],
    price: 76,
    calories: 190,
    prepTime: 6,
    image: "/images/dish-dessert.webp",
    spice: 1,
    badges: [],
    dietary: ["vegan", "gluten-free", "dairy-free"],
    rating: 4.7,
    reviewCount: 143,
  },

  /* ------------------------------- COCKTAILS ------------------------------ */
  {
    id: "smoked-akpeteshie",
    name: "Smoked Akpeteshie Old Fashioned",
    category: "cocktails",
    description:
      "Aged akpeteshie, palm sugar, cocoa bitters and a torched cinnamon stick that perfumes the whole table.",
    ingredients: ["Aged akpeteshie", "Palm sugar", "Cocoa bitters", "Torched cinnamon", "Orange peel"],
    price: 125,
    calories: 210,
    prepTime: 7,
    image: "/images/dish-cocktail.webp",
    spice: 0,
    badges: ["signature", "best-seller"],
    dietary: ["vegan", "gluten-free"],
    rating: 5,
    reviewCount: 612,
  },
  {
    id: "hibiscus-sour",
    name: "Hibiscus Sour",
    category: "cocktails",
    description: "Gin, sorrel reduction, lime and a cloud of egg white. Deep ruby, bracingly fresh.",
    ingredients: ["Gin", "Sorrel reduction", "Lime", "Egg white", "Angostura"],
    price: 105,
    calories: 180,
    prepTime: 6,
    image: "/images/dish-cocktail.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["gluten-free"],
    rating: 4.9,
    reviewCount: 488,
  },
  {
    id: "coconut-negroni",
    name: "Coconut Fat-Washed Negroni",
    category: "cocktails",
    description: "Campari, sweet vermouth and gin washed in toasted coconut oil. Silk with a bitter edge.",
    ingredients: ["Gin", "Campari", "Sweet vermouth", "Toasted coconut oil", "Grapefruit"],
    price: 118,
    calories: 200,
    prepTime: 5,
    image: "/images/dish-cocktail.webp",
    spice: 0,
    badges: ["chef-recommendation"],
    dietary: ["vegan", "gluten-free"],
    rating: 4.8,
    reviewCount: 271,
  },
  {
    id: "pepper-margarita",
    name: "Scotch Bonnet Margarita",
    category: "cocktails",
    description: "Tequila, lime, agave and a whisper of scotch bonnet, with a smoked salt rim.",
    ingredients: ["Blanco tequila", "Lime", "Agave", "Scotch bonnet", "Smoked salt"],
    price: 110,
    calories: 195,
    prepTime: 5,
    image: "/images/dish-cocktail.webp",
    spice: 2,
    badges: [],
    dietary: ["vegan", "gluten-free"],
    rating: 4.8,
    reviewCount: 355,
  },

  /* ---------------------------------- WINE -------------------------------- */
  {
    id: "chablis-fourchaume",
    name: "Chablis 1er Cru, Fourchaume 2021",
    category: "wine",
    description: "Flint, citrus and sea salt. The natural partner to our black cod.",
    ingredients: ["Chardonnay", "Burgundy, France"],
    price: 165,
    calories: 120,
    prepTime: 3,
    image: "/images/event-wine.webp",
    spice: 0,
    badges: ["chef-recommendation"],
    dietary: ["vegan"],
    rating: 4.9,
    reviewCount: 96,
    serves: "175ml glass · bottle ₵820",
  },
  {
    id: "ridge-estate-cabernet",
    name: "Cabernet Sauvignon, Ridge Estate 2019",
    category: "wine",
    description: "Cassis, cedar and graphite, with the structure to stand up to dry-aged beef.",
    ingredients: ["Cabernet Sauvignon", "Santa Cruz Mountains, USA"],
    price: 210,
    calories: 130,
    prepTime: 3,
    image: "/images/event-wine.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["vegan"],
    rating: 4.9,
    reviewCount: 74,
    serves: "175ml glass · bottle ₵1,180",
  },
  {
    id: "billecart-rose",
    name: "Champagne, Billecart-Salmon Brut Rosé",
    category: "wine",
    description: "Wild strawberry and brioche, a fine persistent bead. Our default celebration.",
    ingredients: ["Pinot Noir", "Chardonnay", "Champagne, France"],
    price: 295,
    calories: 140,
    prepTime: 3,
    image: "/images/event-wine.webp",
    spice: 0,
    badges: ["best-seller"],
    dietary: ["vegan"],
    rating: 5,
    reviewCount: 158,
    serves: "150ml glass · bottle ₵1,650",
  },

  /* ------------------------------- ZERO PROOF ----------------------------- */
  {
    id: "sobolo-spritz",
    name: "Sobolo Spritz",
    category: "mocktails",
    description: "House sorrel steeped with cloves and pineapple skin, lengthened with soda and citrus.",
    ingredients: ["Sorrel", "Clove", "Pineapple", "Soda", "Lime"],
    price: 62,
    calories: 90,
    prepTime: 4,
    image: "/images/dish-cocktail.webp",
    spice: 0,
    badges: ["best-seller"],
    dietary: ["vegan", "gluten-free"],
    rating: 4.9,
    reviewCount: 407,
  },
  {
    id: "ginger-tamarind-cooler",
    name: "Ginger & Tamarind Cooler",
    category: "mocktails",
    description: "Cold-pressed ginger, tamarind, honey and a lot of ice. It bites back, politely.",
    ingredients: ["Ginger", "Tamarind", "Honey", "Lime", "Soda"],
    price: 58,
    calories: 100,
    prepTime: 4,
    image: "/images/dish-cocktail.webp",
    spice: 1,
    badges: ["popular"],
    dietary: ["gluten-free"],
    rating: 4.8,
    reviewCount: 233,
  },
  {
    id: "coconut-pandan-cold",
    name: "Coconut Pandan Shake",
    category: "mocktails",
    description: "Young coconut blended with pandan and vanilla. Dessert pretending to be a drink.",
    ingredients: ["Young coconut", "Pandan", "Vanilla", "Coconut cream"],
    price: 66,
    calories: 210,
    prepTime: 5,
    image: "/images/dish-cocktail.webp",
    spice: 0,
    badges: [],
    dietary: ["vegan", "dairy-free"],
    rating: 4.7,
    reviewCount: 129,
  },

  /* ----------------------------- SOFT DRINKS ------------------------------ */
  {
    id: "pressed-juice",
    name: "Morning Press",
    category: "drinks",
    description: "Pineapple, cucumber, ginger and mint, pressed to order.",
    ingredients: ["Pineapple", "Cucumber", "Ginger", "Mint"],
    price: 48,
    calories: 120,
    prepTime: 4,
    image: "/images/bar-counter.webp",
    spice: 0,
    badges: [],
    dietary: ["vegan", "gluten-free"],
    rating: 4.7,
    reviewCount: 188,
  },
  {
    id: "still-sparkling",
    name: "Still or Sparkling",
    category: "drinks",
    description: "Filtered and carbonated in house. Bottomless during lunch service.",
    ingredients: ["Filtered water"],
    price: 24,
    calories: 0,
    prepTime: 1,
    image: "/images/bar-counter.webp",
    spice: 0,
    badges: [],
    dietary: ["vegan", "gluten-free"],
    rating: 4.5,
    reviewCount: 61,
  },

  /* ------------------------------ COFFEE & TEA ---------------------------- */
  {
    id: "flat-white",
    name: "Flat White",
    category: "coffee",
    description: "Ethiopia Guji, roasted weekly, pulled short with silk-textured milk.",
    ingredients: ["Ethiopia Guji espresso", "Whole milk"],
    price: 42,
    calories: 130,
    prepTime: 4,
    image: "/images/dish-brunch.webp",
    spice: 0,
    badges: ["popular"],
    dietary: ["vegetarian"],
    rating: 4.9,
    reviewCount: 512,
  },
  {
    id: "spiced-tea",
    name: "Grains of Selim Tea",
    category: "coffee",
    description: "Hwentia pods, clove and lemongrass steeped long. Traditional, and quietly medicinal.",
    ingredients: ["Grains of selim", "Clove", "Lemongrass", "Honey"],
    price: 38,
    calories: 60,
    prepTime: 6,
    image: "/images/dish-brunch.webp",
    spice: 0,
    badges: [],
    dietary: ["vegan", "gluten-free"],
    rating: 4.7,
    reviewCount: 141,
  },
];

/* -------------------------------------------------------------------------- */
/*                             Derived selectors                              */
/* -------------------------------------------------------------------------- */

const DISH_INDEX = new Map(DISHES.map((dish) => [dish.id, dish]));

export function getDish(id: string): Dish | undefined {
  return DISH_INDEX.get(id);
}

export function getDishesByCategory(category: MenuCategoryId): Dish[] {
  return DISHES.filter((dish) => dish.category === category);
}

export function getCategory(id: MenuCategoryId): MenuCategory | undefined {
  return MENU_CATEGORIES.find((category) => category.id === id);
}

export function isMenuCategoryId(value: string | null | undefined): value is MenuCategoryId {
  return !!value && MENU_CATEGORIES.some((category) => category.id === value);
}

/** Hero-worthy dishes for the home page showcase. */
export const FEATURED_DISH_IDS = [
  "miso-black-cod",
  "tomahawk",
  "smoked-jollof",
  "fire-shellfish-platter",
  "truffle-tagliatelle",
  "chocolate-dome",
] as const;

export const FEATURED_DISHES = FEATURED_DISH_IDS.map((id) => DISH_INDEX.get(id)!).filter(Boolean);

export const SIGNATURE_DISHES = DISHES.filter((dish) => dish.badges.includes("signature"));

export const POPULAR_DISHES = DISHES.filter(
  (dish) => dish.badges.includes("best-seller") || dish.badges.includes("popular"),
);

export const DIETARY_FILTERS = [
  { id: "vegetarian", label: "Vegetarian" },
  { id: "vegan", label: "Vegan" },
  { id: "gluten-free", label: "Gluten free" },
  { id: "dairy-free", label: "Dairy free" },
] as const;
