/**
 * Editorial photography pipeline.
 *
 * Converts the source photography in `public/images` to WebP at a sane maximum
 * width and emits a generated map of base64 LQIP placeholders so every
 * <Image /> can render a blurred preview with zero extra network cost.
 *
 * Run with: npm run images
 */
import { readdir, writeFile, unlink } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const IMAGE_DIR = path.join(process.cwd(), "public", "images");
const OUTPUT_TS = path.join(process.cwd(), "src", "lib", "generated", "blur-data.ts");
const MAX_WIDTH = 2000;
const QUALITY = 80;

const files = (await readdir(IMAGE_DIR)).filter((f) => /\.(png|jpe?g)$/i.test(f));

/** @type {Record<string, { blurDataURL: string; width: number; height: number }>} */
const manifest = {};

for (const file of files.sort()) {
  const abs = path.join(IMAGE_DIR, file);
  const slug = file.replace(/\.(png|jpe?g)$/i, "");
  const webpName = `${slug}.webp`;
  const webpPath = path.join(IMAGE_DIR, webpName);

  const image = sharp(abs).rotate();
  const meta = await image.metadata();

  const info = await image
    .clone()
    .resize({ width: Math.min(MAX_WIDTH, meta.width ?? MAX_WIDTH), withoutEnlargement: true })
    .webp({ quality: QUALITY, effort: 6 })
    .toFile(webpPath);

  const lqip = await sharp(abs)
    .resize(20, null, { fit: "inside" })
    .blur(1.1)
    .webp({ quality: 45 })
    .toBuffer();

  manifest[`/images/${webpName}`] = {
    blurDataURL: `data:image/webp;base64,${lqip.toString("base64")}`,
    width: info.width,
    height: info.height,
  };

  await unlink(abs);
  console.log(`✓ ${webpName}  ${info.width}×${info.height}  ${(info.size / 1024).toFixed(0)}kb`);
}

const banner = `/**
 * AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
 * Blur placeholders + intrinsic dimensions for local editorial photography.
 */
`;

await writeFile(
  OUTPUT_TS,
  `${banner}
export interface ImageMeta {
  readonly blurDataURL: string;
  readonly width: number;
  readonly height: number;
}

export const IMAGE_META = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageMeta>;

export type LocalImageSrc = keyof typeof IMAGE_META;
`,
  "utf8",
);

console.log(`\nWrote ${Object.keys(manifest).length} entries to ${path.relative(process.cwd(), OUTPUT_TS)}`);
